_target_: multi_emotion_recognition.model.lm.MultiEmoModel

defaults:
  - optimizer: hf_adamw
  - scheduler: linear_with_warmup


arch: bert-base-uncased
dataset: ${data.dataset}
neg_weight: 1

num_freeze_layers: 0
freeze_epochs: -1

save_outputs: ${training.save_outputs}
exp_id: null

measure_attrs_runtime: False

use_hashtag: False
use_senti_tree: False
use_emo_cor: False

hashtag_emb_dim: 80
phrase_emb_dim: 80
senti_emb_dim: 10