_target_: src.model.lm.MultiEmoModel

defaults:
  - optimizer: hf_adamw
  - scheduler: linear_with_warmup


arch: bert-base-uncased
dataset: ${data.dataset}
num_classes: ${data.num_classes}
neg_weight: 1

num_freeze_layers: 0
freeze_epochs: -1

save_outputs: ${training.save_outputs}
exp_id: null

measure_attrs_runtime: False


use_hashtag: False
use_senti_tree: False
use_emo_cor: False

hashtag_emb_dim: 80
phrase_emb_dim: 80
senti_emb_dim: 10
phrase_num: 20
max_length: 128
